databases:
  - name: postgres
    ipAllowList: []
    databaseName: contact_manager_system
    user: james
    service: free

services:
  - type: web
    name: contact_management_system
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false